[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]

# -- Settings for CREATE2, see https://getfoundry.sh/guides/deterministic-deployments-using-create2/
solc = "0.8.27"
evm_version = "Prague"
bytecode_hash = "none"
cbor_metadata = false
always_use_create_2_factory = true
optimizer = true
optimizer_runs = 200
# --
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

# File system permissions for reading JSON fixtures
fs_permissions = [{ access = "read", path = "./script/input/" }]

[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-function", "mixed-case-variable", "pascal-case-struct"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
